import type { Metadata } from 'next';
import Link from 'next/link';
import { ConsentSettingsButton } from '@/components/analytics-consent';
import { openGraph } from '@/lib/site';
const description='Hva Middagen.no gjør med søk og valg, og hvordan Google Analytics bare brukes hvis du sier ja.';
export const metadata:Metadata={title:'Personvern',description,alternates:{canonical:'/personvern/'},openGraph:openGraph('/personvern/','Personvern',description)};
export default function Page(){return <main id="hovedinnhold" className="content-page"><p className="eyebrow">PERSONVERN</p><h1>Middag uten profil.</h1><p>Sist oppdatert 4. oktober 2026.</p>
<h2>Søk og valg blir i nettleseren</h2><p>Ingredienssøk og filtrering foregår i nettleseren. Appen sender ikke det du skriver til en søketjeneste, lagrer ikke valgene på en server og krever ingen innlogging eller profil. Forslag, søk og filtre huskes midlertidig i denne nettleserfanen, slik at du kan gå tilbake fra en oppskrift. Denne lagringen sendes ikke til oss og avsluttes normalt når fanen lukkes. Nettleseren kan gjenopprette den hvis du gjenåpner en tidligere økt.</p>
<h2>Google Analytics bare hvis du sier ja</h2><p>Vi bruker Google Analytics 4 for å se hvilke funksjoner som blir brukt, og hva som bør bli bedre. Skriptet fra Google lastes ikke før du har valgt «Tillat analyse». Velger du «Kun nødvendige», eller lar være å svare, sendes ingenting til Google Analytics.</p><p>Når analyse er tillatt, registrerer Google Analytics sidevisninger og kan registrere enkelte standardhendelser, som hvor langt du scroller og klikk på lenker til andre nettsteder. I middagsverktøyet registrerer vi i tillegg:</p><ul><li>når du ber om middagstips, ser tre nye eller lar oss bestemme</li><li>når du bruker veiviseren, med valgt tid, type middag og prisnivå</li><li>om et ingredienssøk ga treff, og hvilken ingrediens fra vårt utvalg søket ble tolket som</li><li>hvilken rett du åpner, og om du endrer antall porsjoner</li></ul><p>Teksten du skriver i søkefeltet sendes ikke, og vi oppretter ingen bruker-ID. Som ved alle nettverkskall mottar Google tekniske opplysninger som IP-adresse og nettlesertype. Google Analytics lagrer informasjonskapslene <code>_ga</code> og <code>_ga_RB2YJ9DF6M</code>, som ifølge Google har en standard levetid på to år.</p><p>Samtykket gjelder bare analyse. Google-signaler og annonsepersonalisering er slått av, og vi bruker ikke Google Ads, remarketing eller annonsepiksler.</p>
<h2>Slik endrer du valget</h2><p>Du kan endre valget når som helst, her eller med «Endre analysevalg» nederst på hver side. Trekker du samtykket tilbake, stopper målingen med en gang, og Google Analytics-informasjonskapslene fra Middagen.no slettes i nettleseren din. Data som allerede er sendt til Google, slettes ikke av dette.</p><div><ConsentSettingsButton className="button button-secondary"/></div><p>Valget lagres i nettleserens lokale lagring, slik at vi ikke spør på nytt ved neste besøk. Det sendes ikke til oss.</p>
<h2>Hvem står bak, og hvor ligger siden</h2><p>Middagen.no drives av Andreas Swane / Swane Creative og ligger hos Vercel. Som vertstjeneste mottar Vercel tekniske opplysninger, for eksempel IP-adresse, når sidene lastes.</p>
<h2>Henvendelser</h2><p>Sender du oss e-post, mottar vi opplysningene du selv tar med for å kunne svare. Ikke send sensitive opplysninger. Du finner kontaktinformasjon på <Link href="/kontakt">kontaktsiden</Link>.</p></main>}
