import fs from 'node:fs';
import assert from 'node:assert/strict';
import { load } from './test-support.mjs';
const meals=JSON.parse(fs.readFileSync('lib/meals.json','utf8'));
const {filterMeals,matchIngredient,suggest}=load('lib/engine.ts');
const all={time:'all',type:'all',price:'all'};
let checks=0;
function test(name,fn){fn();checks++;console.log(`PASS ${name}`);}
test('42 unique complete recipe records',()=>{assert.equal(meals.length,42);assert.equal(new Set(meals.map(m=>m.slug)).size,42);for(const m of meals){assert.match(m.slug,/^[a-z0-9]+(?:-[a-z0-9]+)*$/);assert.ok(m.ingredients.length>=4);assert.ok(m.instructions.length>=4);assert.ok(m.instructions.every(x=>x.length>25));assert.ok(m.timeMinutes>=10&&m.timeMinutes<=90);assert.equal(m.baseServings,4);assert.ok(['kjott','fisk','vegetar'].includes(m.category));assert.ok(['billig','vanlig','litt-ekstra'].includes(m.costTier));for(const i of m.ingredients)assert.ok(i.name&&(i.quantity===null||i.quantity>0));}});
test('every required everyday ingredient yields at least three real matches',()=>{for(const word of ['kylling','kjøttdeig','laks','pasta','poteter','egg','torsk','pølser','ris']){const {ingredient}=matchIngredient(word,meals);assert.equal(ingredient,word);assert.ok(filterMeals(meals,all,ingredient).length>=3,word);}});
test('case, whitespace, Norwegian letters, aliases and typos',()=>{for(const [query,want] of Object.entries({'  KYLLING  ':'kylling',kyling:'kylling',kyllingfilet:'kyllingfilet',kjottdeig:'kjøttdeig',spaghetti:'spaghetti',potet:'poteter',polser:'pølser',laksefilet:'laks',gulrøtter:'gulrot',tomater:'tomat',linser:'linser',halloumi:'vegetarisk halloumi','Jeg har kylling':'kylling'}))assert.equal(matchIngredient(query,meals).ingredient,want,query);});
test('unknown, empty, ambiguous and multiple ingredients do not fabricate matches',()=>{for(const query of ['','   ','sjokolade','kylling og laks','østerssaus','<script>alert(1)</script>'])assert.equal(matchIngredient(query,meals).ingredient,null,query);});
test('63 filter combinations keep time, type and cost constraints',()=>{for(const time of ['all','15','30'])for(const type of ['all','familie','kjott','fisk','vegetar','lett','unknown'])for(const price of ['all','billig','vanlig']){const f={time,type,price};const pool=filterMeals(meals,f);const picked=suggest(pool,27);assert.ok(picked.length<=3&&picked.length<=pool.length);for(const m of picked){assert.ok(time==='all'||m.timeMinutes<=Number(time));assert.ok(type==='all'||(type==='familie'?m.familyFriendly:type==='lett'?m.mealTags.includes('lett'):m.category===type));assert.ok(price==='all'||(price==='billig'?m.costTier==='billig':m.costTier!=='litt-ekstra'));}}});
test('same seed produces same output, no duplicate cards, unseen meals preferred',()=>{for(let seed=1;seed<=40;seed++){const a=suggest(meals,seed);const b=suggest(meals,seed);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(new Set(a.map(m=>m.id)).size,3);const c=suggest(meals,seed+1,a.map(m=>m.id));assert.ok(c.every(m=>!a.some(x=>x.id===m.id)));assert.equal(new Set(a.map(m=>m.category)).size,3);}});
test('zero/one/two matches remain honest',()=>{for(let n=0;n<=2;n++){const result=suggest(meals.slice(0,n),4);assert.equal(result.length,n);}});
test('vegetarian tags do not include meat or fish',()=>{const animal=['kylling','kjøttdeig','laks','torsk','tunfisk','reker','pølser','skinke','svinekoteletter','fiskekaker'];for(const m of filterMeals(meals,{...all,type:'vegetar'}))assert.ok(![...m.mainIngredients,...m.secondaryIngredients].some(i=>animal.includes(i)));});
console.log(JSON.stringify({checks,recipes:meals.length,quick15:meals.filter(m=>m.timeMinutes<=15).length,quick30:meals.filter(m=>m.timeMinutes<=30).length,categories:Object.fromEntries(['kjott','fisk','vegetar'].map(c=>[c,meals.filter(m=>m.category===c).length]))},null,2));
